### ISSUE TITLE
youtube import is too slow

### ISSUE THREAD

**Issue by 2biter** [sheharyaar/SLAM-Reboot#2]
Allday to download ;(

**Comment by sheharyaar** [comment]
Ok @2biter I will look into it. Attach the youtube link that you tried to download.

Thanks

**Comment by sheharyaar** [comment]
@2biter I have fixed the issue, Kindly see the repo again, download and test it. Please reply after testing.
Thanks.

**Comment by 2biter** [comment]
Perfect.. Rly appreciated bro
