### ISSUE TITLE
TF2 CELT Codec

### ISSUE THREAD

**Issue by Capybaron** [sheharyaar/SLAM-Reboot#3]
Did you update that aswell?

**Comment by sheharyaar** [comment]
No @PeterPumpkinEater69real, will check and update soon! If you have any information that can help me, please share it.
Thanks for opening the issue.

**Comment by sheharyaar** [comment]
Since I was not able to test the issue. I am closing this down. If you have any information to share in details, please reopen the issue and add it. Thanks!
