### ISSUE TITLE
Error :O

### ISSUE THREAD

**Issue by 2biter** [sheharyaar/SLAM-Reboot#4]
--------------------2022-02-13 오후 12:15:08 UTC--------------------
System.ArgumentOutOfRangeException: 인덱스 및 길이는 문자열 내의 위치를 참조해야 합니다.
매개 변수 이름: length
   위치: System.String.Substring(Int32 startIndex, Int32 length)
   위치: SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e) 파일 C:\Users\sheha\Documents\GitHub\SLAM-Reboot\SLAM\YTImport.vb:줄 83
--------------------2022-02-13 오후 12:20:07 UTC--------------------
System.ArgumentOutOfRangeException: 인덱스 및 길이는 문자열 내의 위치를 참조해야 합니다.
매개 변수 이름: length
   위치: System.String.Substring(Int32 startIndex, Int32 length)
   위치: SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e) 파일 C:\Users\sheha\Documents\GitHub\SLAM-Reboot\SLAM\YTImport.vb:줄 83

This is error log ;(

**Comment by sheharyaar** [comment]
@2biter It must be due to very long video filename. I will look into it. Can you please attach the link of the video you tried to convert.

**Comment by 2biter** [comment]
> @2biter It must be due to very long video filename. I will look into it. Can you please attach the link of the video you tried to convert.

**Comment by sheharyaar** [comment]
@2biter Thanks for sharing this, I will look into it and update soon!

**Comment by sheharyaar** [comment]
Please check the new release and test the link you sent and update me here so that I can close the issue. Cheers! 😄

**Comment by 2biter** [comment]
> Please check the new release and test the link you sent and update me here so that I can close the issue. Cheers! 😄

It's working perfectly Thanks
