### ISSUE TITLE
convert not working

### ISSUE THREAD

**Issue by 2biter** [sheharyaar/SLAM-Reboot#7]
Download working but cannot convert

**Comment by sheharyaar** [comment]
Is this same as : https://github.com/sheharyaar/SLAM-Reboot/issues/6 ?

**Comment by 2biter** [comment]
> Is this same as : #6 ?

Oh same :D
I downloaded yt-dlp and fixed

**Comment by sheharyaar** [comment]
Cool then, I will be closing the issue.
